### ISSUE TITLE
TODOs: Porting Gekko-UI to Quasar Framework

### ISSUE THREAD

**Issue by H256** [H256/gekko-quasar-ui#1]
### Todo:
- [x]  convert base assets etc. to quasar
- [x] revamp ajax and store module with axios
- [x] convert **config-pages** to quasar
- [x] convert **data-pages** to quasar
- [x] convert **backtester-pages** to quasar
- [x] convert **live-gekko-pages** to quasar
- [x] replace global moment with imported module
- [x] replace global humanize-duration dependency with imported module
- [x] replace custom ajax dependency with calls to axios

**Comment by H256** [comment]
Conversion done.
