### ISSUE TITLE
TODO: Enhancement ideas - round 1

### ISSUE THREAD

**Issue by H256** [H256/gekko-quasar-ui#2]
### Todo:
- [ ] add dashboard overview for all running processes (imports, live-gekkos, backtest)
- [x] add liveview of running imports into sidebar or top toolbar
- [x] try to build backtest graph with echarts instead of d3 custom plot
- [ ] impement round(), round2() and humanizeDuration as Vue-Filter-Pipes 
- [ ] implement getters for store, so that calling from within components is easier...
- [ ] refactor all components to layouts -> pages with subroutes and tabs so that pages don't get too long
- [ ] refactor _humanizeDuration_, _toml_ and _moment_ to Quasar Plugins, so they can be called with this.$<module> from within components.
- [ ] refactor axios calls on templates to store calls or repository pattern
- [ ] in the backtester, enable users to copy current strategy settings to clipboard as json notation for use in cli-gekko.

**Comment by BlackHoleDevs** [comment]
Hello ! Would like to say that i am impressed with amount of work which you did. 
my proposition for small improvement is to add possibility to start paper/live trader from back test page .
Second thing which I wanted from you is to ask if you will be interested to work in the First Orbital Bank in near future ? (kick-starter campaign and ICO are being prepared right now, and we patented whole bunch of stuff)

**Comment by H256** [comment]
@Exmoond wonderful idea! I've added this to the backtester page. Two buttons appear right under the "backtest" button. One starts a paper trader with all current set settings. The other one start a live trader ;)

Regarding the other I have to decline...

**Comment by BlackHoleDevs** [comment]
Thank you for adding it!  
Got a question, it is normal that quasar build is taking more than 8 minutes on "additional chunk assets processing" or maybe I am doing something wrong?

**Comment by H256** [comment]
@Exmoond On my PC it also takes forever to build - but anyways I'm using it in DEV-mode most of the time, parallel to the original UI.

**Comment by bruno-berchielli** [comment]
Great work with Quasar! I'm loving it!

What about the possibility to select multiple pairs in the backtest list and run them simultaneously, separating each result in a tab with the pair name below the "Backtest" button?

**Comment by H256** [comment]
Basically it's a good idea, but I'm afraid that at the moment the server can't handle parallel backtests.

**Comment by BlackHoleDevs** [comment]
my proposition for parallel testing is to use pm2 production process manager.

**Comment by bruno-berchielli** [comment]
Doesn’t need to be in parallel. Anyway, if each new backtest run was “stored” in a tab it could be useful for the user to quickly compare results! 😉

The tab could have a X so the user could quickly dismiss it.

Thanks

**Comment by H256** [comment]
Currently the plan is to wait until 0.6 of Gekko is out (because of the changes to the events). After that I'm looking at creating a nicer backtester view ;)

**Comment by olexiyb** [comment]
@Exmoond in my case build took 
Version: webpack 4.19.1
Time: 23384ms (23 seconds)
I have drive Samsung SSD 950 PRO and Intel i7-7700K CPU
